apiVersion: v1
data:
  load_definition.json: ewogICJ2aG9zdHMiOiBbCiAgICB7CiAgICAgICJuYW1lIjogIi8iCiAgICB9CiAgXSwKICAicG9saWNpZXMiOiBbCiAgICB7CiAgICAgICJuYW1lIjogImhhLWFsbCIsCiAgICAgICJwYXR0ZXJuIjogIi4qIiwKICAgICAgInZob3N0IjogIi8iLAogICAgICAicHJpb3JpdHkiOiAwLAogICAgICAiZGVmaW5pdGlvbiI6IHsKICAgICAgICAiaGEtbW9kZSI6ICJleGFjdGx5IiwKICAgICAgICAiaGEtcGFyYW1zIjogMgogICAgICB9CiAgICB9LAogICAgewogICAgICAibmFtZSI6ICJhdXRvZXhwaXJlLWNlbGVyeWV2LXF1ZXVlcyIsCiAgICAgICJwYXR0ZXJuIjogImNlbGVyeWV2XFwuLioiLAogICAgICAidmhvc3QiOiAiLyIsCiAgICAgICJwcmlvcml0eSI6IDEwLAogICAgICAiYXBwbHktdG8iOiAicXVldWVzIiwKICAgICAgImRlZmluaXRpb24iOiB7CiAgICAgICAgImV4cGlyZXMiOiAzMDAwMDAKICAgICAgfQogICAgfSwKICAgIHsKICAgICAgIm5hbWUiOiAiYXV0b2V4cGlyZS1jZWxlcnlwaWRib3gtcXVldWVzIiwKICAgICAgInBhdHRlcm4iOiAiLipcXC5jZWxlcnlcXC5waWRib3giLAogICAgICAidmhvc3QiOiAiLyIsCiAgICAgICJwcmlvcml0eSI6IDEwLAogICAgICAiYXBwbHktdG8iOiAicXVldWVzIiwKICAgICAgImRlZmluaXRpb24iOiB7CiAgICAgICAgImV4cGlyZXMiOiAzMDAwMDAKICAgICAgfQogICAgfQogIF0KfQ==
kind: Secret
metadata:
  name: rabbitmq-definition-{{ include "chart.fullname" . }}
  labels:
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
