apiVersion: v1
data:
  load_definition.json: ewogICJwb2xpY2llcyI6IFsKICAgIHsKICAgICAgIm5hbWUiOiAiaGEtYWxsIiwKICAgICAgInBhdHRlcm4iOiAiLioiLAogICAgICAidmhvc3QiOiAiLyIsCiAgICAgICJwcmlvcml0eSI6IDAsCiAgICAgICJkZWZpbml0aW9uIjogewogICAgICAgICJoYS1tb2RlIjogImV4YWN0bHkiLAogICAgICAgICJoYS1wYXJhbXMiOiAyCiAgICAgIH0KICAgIH0sCiAgICB7CiAgICAgICJuYW1lIjogImF1dG9leHBpcmUtY2VsZXJ5ZXYtcXVldWVzIiwKICAgICAgInBhdHRlcm4iOiAiY2VsZXJ5ZXZcXC4uKiIsCiAgICAgICJ2aG9zdCI6ICIvIiwKICAgICAgInByaW9yaXR5IjogMTAsCiAgICAgICJhcHBseS10byI6ICJxdWV1ZXMiLAogICAgICAiZGVmaW5pdGlvbiI6IHsKICAgICAgICAiZXhwaXJlcyI6IDMwMDAwMAogICAgICB9CiAgICB9LAogICAgewogICAgICAibmFtZSI6ICJhdXRvZXhwaXJlLWNlbGVyeXBpZGJveC1xdWV1ZXMiLAogICAgICAicGF0dGVybiI6ICIuKlxcLmNlbGVyeVxcLnBpZGJveCIsCiAgICAgICJ2aG9zdCI6ICIvIiwKICAgICAgInByaW9yaXR5IjogMTAsCiAgICAgICJhcHBseS10byI6ICJxdWV1ZXMiLAogICAgICAiZGVmaW5pdGlvbiI6IHsKICAgICAgICAiZXhwaXJlcyI6IDMwMDAwMAogICAgICB9CiAgICB9CiAgXQp9Cg==
kind: Secret
metadata:
  name: rabbitmq-definition-{{ include "chart.fullname" . }}
  labels:
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
